import { execFile } from "node:child_process";
import { existsSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import type {
  AgentRuntimeAdapter,
  HarnessAuthStatus,
  RuntimeCapability,
  RuntimeContext,
  RuntimeResult,
  RunEvent,
  Usage,
} from "@agentfabric/core";
import { runHarnessCommand } from "./harness.js";

/**
 * DSH (DeepSeek Harness) adapter — protocol shapes verified against the
 * official headless bundle (`@deepseek-ai/dsh-headless`, dsh
 * 0.1.6-alpha.1, one-shot task runner over dsh-base):
 *
 * - `dsh --profile headless --json [--session-id <id>] -- <task>` runs one
 *   task and exits; exit 0 = completed, 1 = aborted or errored.
 * - `--json` projects the run as newline-delimited events on stdout:
 *   `session` (sessionId + cwd) → `status` (turn/step phases; `step_end`
 *   carries that model request's usage) → `text` / `thinking` (projected
 *   from *committed* assistant messages, so retried attempts never reach
 *   the stream) → `tool_call` / `tool_result` (paired by callId) →
 *   `final` (the same lossless answer the default mode prints). A failure
 *   raised outside a turn writes an `error` event and ends without
 *   `final`; a failure inside a turn still ends with `final` (often
 *   empty) — exit code and `turn_end` reason are the failure signal.
 * - `--session-id` adopts the persisted Session with that id — the same
 *   ids the local session discovery lists. The one-shot runner composes
 *   no agent preset, so it refuses every session that carries one —
 *   i.e. sessions from the desktop/web surfaces — as well as subagent /
 *   forked sessions and sessions whose recorded cwd differs from the
 *   run's working directory. Those refusals happen before the task runs
 *   and keep DSH's own message; such sessions still adopt into
 *   AgentFabric (history projection) and continue via handoff.
 * - Runs on the harness's own DeepSeek account (harness-native, v6 §2);
 *   AgentFabric binds no Provider/Model. The task runs in the profile's
 *   own model selection and sandbox defaults.
 */

interface DshEvent {
  type?: string;
  sessionId?: unknown;
  cwd?: unknown;
  phase?: unknown;
  turn?: unknown;
  step?: unknown;
  usage?: DshUsage;
  reason?: { kind?: unknown };
  text?: unknown;
  callId?: unknown;
  tool?: unknown;
  input?: unknown;
  status?: unknown;
  result?: unknown;
  message?: unknown;
  [key: string]: unknown;
}

export function dshBin(): string {
  return process.env.AGENTFABRIC_DSH_BIN ?? "dsh";
}

/** $DSH_HOME resolution mirrors the harness's own launcher. */
function dshHome(): string {
  return process.env.DSH_HOME ?? join(homedir(), ".dsh");
}

/**
 * The headless bundle's profile directory. DSH boots profiles from
 * $DSH_HOME/profiles; a missing one fails loudly in the harness itself
 * ("create it with 'dsh plugin --profile <name> add <package>'") — the
 * auth check surfaces the same remedy before a run is attempted.
 */
export function dshHeadlessProfileDir(): string {
  return join(dshHome(), "profiles", "headless");
}

/**
 * DSH harness capabilities (spec v1 §17): native sessions with resume,
 * streamed events, workspace-aware. Handoff summaries are generated by
 * AgentFabric (assisted) — the headless runner has no summary mode.
 */
export const dshCapabilities: Partial<RuntimeCapability> = {
  supportsNativeSession: true,
  supportsNativeResume: true,
  supportsStreamingEvents: true,
  supportsHandoffGeneration: false,
  supportsWorkspace: true,
  supportsInteractiveExecution: false,
};

/**
 * Containerized DSH has no official runtime image; without a configured
 * `image` the effective-capability computation narrows these to "cannot
 * run" and the adapter refuses to start (same contract as pi, v3 §10).
 * The opaque native state (~/.dsh: sessions, profiles, credentials) is
 * what must be mounted for Containerized Native Resume.
 */
export const dshNativeStateMountPath = "/root/.dsh";

/* ------------------------------------------------------------------ */
/* Event mapping (v3 §4/§5)                                            */
/* ------------------------------------------------------------------ */

/** tool_call → identity a later tool_result needs to complete itself. */
export interface DshMapperState {
  /** callId → the tool that declared the call (tool_result carries none). */
  tools: Map<string, string>;
  /** callId → the file path (write/edit results map to file activity). */
  files: Map<string, { path: string; action: "add" | "update" }>;
}

export function newDshEventMapperState(): DshMapperState {
  return { tools: new Map(), files: new Map() };
}

interface DshUsage {
  inputTokens?: unknown;
  outputTokens?: unknown;
  totalTokens?: unknown;
  cacheReadTokens?: unknown;
}

/**
 * Maps one dsh-headless JSONL event to AgentFabric standard events.
 * `text` events are the committed per-message contents — they become the
 * agent.message stream (pi's message_end equivalent); `final` repeats the
 * last of them and is kept only as bookkeeping, so nothing is emitted
 * twice.
 */
export function mapDshEvent(
  raw: string,
  runId: string,
  seq: () => number,
  state: DshMapperState
): RunEvent | RunEvent[] | null {
  let evt: DshEvent;
  try {
    evt = JSON.parse(raw) as DshEvent;
  } catch {
    return null;
  }
  const type = evt.type ?? "unknown";
  const timestamp = new Date().toISOString();
  const base = { id: `evt_${runId}_${seq()}`, runId, seq: seq(), timestamp };

  switch (type) {
    /* ---- session header: every run opens with the identity it used ---- */
    case "session":
      return {
        ...base,
        type: "run.progress",
        level: "info",
        source: "dsh",
        data: { phase: "session", sessionId: evt.sessionId, cwd: evt.cwd },
      };

    /* ---- turn / step lifecycle → run progress; usage flows through
            parseDshUsage so it is not duplicated here ---- */
    case "status": {
      const phase = typeof evt.phase === "string" ? evt.phase : "unknown";
      return {
        ...base,
        type: "run.progress",
        level: "debug",
        source: "dsh",
        data: {
          phase,
          ...(typeof evt.turn === "number" ? { turn: evt.turn } : {}),
          ...(typeof evt.step === "number" ? { step: evt.step } : {}),
          ...(evt.reason && typeof evt.reason === "object" ? { reason: evt.reason } : {}),
        },
      };
    }

    case "thinking": {
      const text = typeof evt.text === "string" ? evt.text : "";
      if (!text.trim()) return null;
      return { ...base, type: "agent.thinking", level: "debug", source: "dsh", data: { content: text } };
    }

    case "text": {
      const text = typeof evt.text === "string" ? evt.text : "";
      if (!text.trim()) return null;
      return {
        ...base,
        type: "agent.message",
        level: "info",
        source: "dsh",
        data: { content: text, role: "assistant" },
      };
    }

    /* ---- tool execution: the call declares identity, the result
            completes it (tool_result names only the callId) ---- */
    case "tool_call": {
      const callId = typeof evt.callId === "string" ? evt.callId : "";
      const tool = typeof evt.tool === "string" && evt.tool ? evt.tool : "tool";
      const input = evt.input && typeof evt.input === "object" ? (evt.input as Record<string, unknown>) : {};
      if (callId) state.tools.set(callId, tool);
      if (tool === "bash") {
        return {
          ...base,
          type: "shell.command",
          level: "info",
          source: "dsh",
          data: { command: String(input.command ?? "(bash)"), toolCallId: callId || undefined },
        };
      }
      if (tool === "write" || tool === "edit") {
        const path = String(input.file_path ?? input.path ?? "(file)");
        if (callId) state.files.set(callId, { path, action: tool === "write" ? "add" : "update" });
      }
      return {
        ...base,
        type: "tool.started",
        level: "info",
        source: "dsh",
        data: { tool, toolCallId: callId || undefined, args: input },
      };
    }

    case "tool_result": {
      const callId = typeof evt.callId === "string" ? evt.callId : "";
      const isError = evt.status !== "completed";
      const tool = (callId ? state.tools.get(callId) : undefined) ?? "tool";
      if (callId) {
        state.tools.delete(callId);
      }
      if (tool === "bash") {
        return {
          ...base,
          type: "shell.output",
          level: isError ? "warn" : "info",
          source: "dsh",
          data: { output: evt.result, isError, toolCallId: callId || undefined },
        };
      }
      const file = callId ? state.files.get(callId) : undefined;
      const completed: RunEvent = {
        ...base,
        type: "tool.completed",
        level: isError ? "warn" : "info",
        source: "dsh",
        data: { tool, toolCallId: callId || undefined, result: evt.result, isError },
      };
      if (file) {
        return [
          {
            ...base,
            type: file.action === "add" ? "file.created" : "file.modified",
            level: "info",
            source: "dsh",
            data: { path: file.path },
          },
          completed,
        ];
      }
      return completed;
    }

    /* ---- final is the runner's bookkeeping: the same text already
            streamed as the last committed message ---- */
    case "final":
      return {
        ...base,
        type: "run.progress",
        level: "debug",
        source: "dsh",
        data: { phase: "final", ...(typeof evt.text === "string" ? { text: evt.text } : {}) },
      };

    /* ---- failure raised outside a turn (the stream then ends without
            final); in-turn failures end with turn_end + exit 1 ---- */
    case "error":
      return {
        ...base,
        type: "runtime.error",
        level: "error",
        source: "dsh",
        data: { error: String(evt.message ?? raw) },
      };

    default:
      // Unknown event types stay visible as raw debug events (v3 §5).
      return { ...base, type: "log", level: "debug", source: "dsh", data: { line: raw } };
  }
}

/**
 * Extracts the native session reference from the stream's opening
 * `session` event. The value stays opaque — AgentFabric stores it for
 * `--session-id` resume.
 */
export function extractDshSessionRef(raw: string): string | undefined {
  try {
    const evt = JSON.parse(raw) as DshEvent;
    if (evt.type === "session" && typeof evt.sessionId === "string" && evt.sessionId) return evt.sessionId;
    return undefined;
  } catch {
    return undefined;
  }
}

/**
 * Extracts the per-model-request usage from a `step_end` status event —
 * one event per committed step, never cumulative, so each maps to
 * exactly one model request (v3 §8).
 */
export function parseDshUsage(raw: string): Usage | undefined {
  let evt: DshEvent;
  try {
    evt = JSON.parse(raw) as DshEvent;
  } catch {
    return undefined;
  }
  if (evt.type !== "status" || evt.phase !== "step_end" || !evt.usage || typeof evt.usage !== "object") {
    return undefined;
  }
  const u = evt.usage;
  const num = (v: unknown): number => (typeof v === "number" && Number.isFinite(v) ? v : 0);
  return {
    inputTokens: num(u.inputTokens),
    outputTokens: num(u.outputTokens),
    cachedTokens: num(u.cacheReadTokens),
    modelRequests: 1,
  };
}

/**
 * Detects DSH availability using its own surfaces (v6 §2): `dsh
 * --version`, the headless profile directory, and the presence of DSH's
 * credentials file. No credential content is ever read — existence is
 * the only signal AgentFabric looks at; DSH owns its identity end to end.
 */
export async function dshAuthStatus(bin = dshBin()): Promise<HarnessAuthStatus> {
  const version = await new Promise<{ code: number | null; out: string; failed?: Error }>((resolve) => {
    execFile(bin, ["--version"], { timeout: 10_000 }, (err, stdout, stderr) => {
      resolve({
        code: err ? ((err as NodeJS.ErrnoException & { code?: number }).code ?? 1) : 0,
        out: `${stdout ?? ""}${stderr ?? ""}`.trim(),
        failed: err && !stdout ? err : undefined,
      });
    });
  });
  if (version.failed || version.code !== 0 || !version.out) {
    return {
      installed: false,
      loggedIn: false,
      ok: false,
      detail: version.failed ? String(version.failed.message ?? version.failed) : undefined,
      hint: "Install the DSH CLI (`npm install -g @deepseek-ai/dsh`) and make sure `dsh` is on PATH.",
    };
  }
  const versionText = version.out.split("\n")[0]?.trim();
  const profileDir = dshHeadlessProfileDir();
  if (!existsSync(profileDir)) {
    return {
      installed: true,
      loggedIn: false,
      ok: false,
      version: versionText,
      detail: "headless profile not found",
      hint: `Create the headless profile once: dsh plugin --profile headless add @deepseek-ai/dsh-headless`,
    };
  }
  // Existence only — the file is DSH's own credential store (dsh-credentials).
  const loggedIn = existsSync(join(dshHome(), ".credentials.yaml"));
  return {
    installed: true,
    loggedIn,
    ok: loggedIn,
    version: versionText,
    detail: loggedIn ? "DSH credentials detected" : "no DSH credentials found",
    hint: loggedIn
      ? undefined
      : "Run `dsh` once in a terminal to sign in with your DeepSeek account, then retry — AgentFabric never handles DSH credentials itself.",
  };
}

/**
 * Builds the dsh-headless CLI args for a run. `--` ends option parsing so
 * a task text that starts with `-` stays a positional. Native resume
 * passes the harness's own session id (spec v1 §3) — an unknown or
 * preset-mismatched id is DSH's own loud error before the task runs.
 */
function buildArgs(ctx: RuntimeContext): string[] {
  const args = ["--profile", "headless", "--json"];
  if (ctx.runtimeSession?.nativeSessionRef) {
    args.push("--session-id", ctx.runtimeSession.nativeSessionRef);
  }
  args.push("--");
  return args;
}

/**
 * DSH Agent Runtime adapter.
 *
 * One execution loop for both backends (v2 §7/§8/§10): the adapter builds
 * the `dsh --profile headless --json` command and hands it to the
 * execution backend — a local process or a Docker container. Either way,
 * the JSONL stdout is parsed here with the same mapper, the native
 * session id is extracted from the session event, and a stored reference
 * is resumed via `--session-id`.
 */
export const dshAdapter: AgentRuntimeAdapter = {
  kind: "dsh",
  name: "DSH (DeepSeek)",
  capabilities: dshCapabilities,
  nativeStateMountPath: dshNativeStateMountPath,
  credentialSource: "harness-native",
  // No providerCompatibility on purpose: DSH runs on its own account;
  // declaring an empty one would silence the orchestrator's warning while
  // claiming structure it does not have.
  // No defaultImage on purpose: no official DSH runtime image exists; a
  // plain node image would silently break native resume.

  async run(ctx: RuntimeContext): Promise<RuntimeResult> {
    if (ctx.runtime.containerized && !ctx.runtime.image) {
      const message =
        "Containerized DSH requires a DSH Runtime Image (a container whose entrypoint is the dsh CLI with " +
        "its state under /root/.dsh). Configure `image` on the runtime.";
      await ctx.emit("runtime.error", { error: message, backend: "docker", source: "dsh" }, { level: "error" });
      return { error: `Containerized DSH refused to start: ${message}` };
    }
    // Fail fast with an actionable message when the harness's own login
    // or the headless profile is missing (v6 §2).
    const auth = await dshAuthStatus();
    if (!auth.installed || !auth.loggedIn) {
      const message = auth.hint ?? "DSH CLI is not available";
      await ctx.emit(
        "runtime.error",
        { error: message, source: "dsh", installed: auth.installed, loggedIn: auth.loggedIn },
        { level: "error" }
      );
      return { error: message };
    }

    const state = newDshEventMapperState();
    const basePrompt = ctx.run.inputInstruction ?? ctx.task.prompt;
    // Agent-profile system instructions have no native headless flag;
    // deliver them as a leading block instead of silently dropping them.
    const prompt = ctx.systemInstructions?.trim()
      ? `${ctx.systemInstructions.trim()}\n\n---\n\n${basePrompt}`
      : basePrompt;

    return runHarnessCommand(ctx, {
      bin: dshBin(),
      args: buildArgs(ctx),
      prompt,
      source: "dsh",
      image: ctx.runtime.image,
      workspaceContainerPath: "/workspace",
      mapLine: (raw, runId, seq) => mapDshEvent(raw, runId, seq, state),
      extractSessionRef: extractDshSessionRef,
      parseUsage: parseDshUsage,
      describeFailure: ({ lastError }) => (lastError ? { error: lastError } : undefined),
    });
  },

  async cancel(ctx) {
    await ctx.log("DSH run cancelled", "warn");
  },

  async checkAuth() {
    return dshAuthStatus();
  },

  describe() {
    return {
      needsDocker: false,
      needsModel: false,
      cli: dshBin(),
      profile: "headless",
      credentialSource: "harness-native",
      executionBackend: "local",
    };
  },
};
