import type { AgentRuntimeAdapter, RuntimeCapability, RuntimeContext, RuntimeResult, RunEvent } from "@agentfabric/core";
import { runHarnessCommand } from "./harness.js";

interface PiEvent {
  type: string;
  [key: string]: unknown;
}

export function piBin(): string {
  return process.env.AGENTFABRIC_PI_BIN ?? "pi";
}

/**
 * Pi harness capabilities (spec v1 §17): native sessions with resume,
 * streamed events, workspace-aware. Handoff summaries are generated by
 * AgentFabric (assisted) since pi does not provide them.
 */
export const piCapabilities: Partial<RuntimeCapability> = {
  supportsNativeSession: true,
  supportsNativeResume: true,
  supportsStreamingEvents: true,
  supportsHandoffGeneration: false,
  supportsWorkspace: true,
  supportsInteractiveExecution: false,
};

/**
 * Containerized capabilities (v2 §11): with the execution-backend path
 * streaming pi's JSON output to this adapter and the native-state
 * directory mounted into the container, containerized pi has the same
 * native-session semantics as local pi (v2 §10).
 */
export const piContainerizedCapabilities: Partial<RuntimeCapability> = {
  ...piCapabilities,
};

/**
 * Maps a pi JSONL event to an AgentFabric standard event.
 * Pi's JSON mode is less structured than opencode's, so we use a tolerant
 * mapping and never drop a line — unknown types become log lines.
 */
export function mapPiEvent(raw: string, runId: string, seq: () => number): RunEvent | null {
  let evt: PiEvent;
  try {
    evt = JSON.parse(raw) as PiEvent;
  } catch {
    return null;
  }
  const type = evt.type ?? "unknown";
  const timestamp = (evt.timestamp as string) ?? new Date().toISOString();
  const data = { ...(evt as Record<string, unknown>) };
  delete data.type;
  const base = { id: `evt_${runId}_${seq()}`, runId, seq: seq(), timestamp, data };

  const text =
    (evt as Record<string, any>).text ??
    (evt as Record<string, any>).content ??
    (evt as Record<string, any>).message?.content ??
    (evt as Record<string, any>).output;

  if (type === "message") {
    const role = (evt as Record<string, any>).role ?? "assistant";
    return { ...base, type: "agent.message", level: "info", source: "pi", data: { content: text ?? "", role, raw: data } };
  }
  if (type === "tool" || type === "tool_call") {
    const tool = (evt as Record<string, any>).tool?.name ?? (evt as Record<string, any>).tool ?? (evt as Record<string, any>).name ?? "unknown";
    const state = (evt as Record<string, any>).state ?? (evt as Record<string, any>).status;
    const isStart = state === "started" || state === "start" || state === "running" || !state;
    return {
      ...base,
      type: isStart ? "tool.started" : "tool.completed",
      level: "info",
      source: "pi",
      data: { tool, state, ...data },
    };
  }
  if (type === "bash" || type === "shell" || type === "command") {
    const command = (evt as Record<string, any>).command ?? (evt as Record<string, any>).cmd ?? text;
    const state = (evt as Record<string, any>).state;
    if (state === "started" || state === "running") {
      return { ...base, type: "shell.command", level: "info", source: "pi", data: { command, ...data } };
    }
    return { ...base, type: "shell.output", level: "info", source: "pi", data: { line: text ?? command ?? "", ...data } };
  }
  if (type === "error") {
    return { ...base, type: "runtime.error", level: "error", source: "pi", data };
  }
  if (type === "usage") {
    return { ...base, type: "model.response", level: "debug", source: "pi", data };
  }
  if (type === "session" || type === "info") {
    return { ...base, type: "log", level: "info", source: "pi", data: { line: `pi: ${JSON.stringify(data)}` } };
  }
  return { ...base, type: "log", level: "debug", source: "pi", data: { line: raw } };
}

/**
 * Extracts pi's own session identifier from a raw JSONL line, if any.
 * The value stays opaque — AgentFabric only stores it for resume.
 */
export function extractPiSessionRef(raw: string): string | undefined {
  try {
    const evt = JSON.parse(raw) as Record<string, any>;
    const type = evt.type ?? "";
    const candidate =
      evt.sessionId ?? evt.session_id ?? evt.sessionID ??
      (type === "session" ? (evt.id ?? evt.session?.id ?? evt.session) : undefined) ??
      evt.session?.id;
    return typeof candidate === "string" && candidate ? candidate : undefined;
  } catch {
    return undefined;
  }
}

function buildArgs(ctx: RuntimeContext): string[] {
  const args = ["--print", "--mode", "json"];
  if (ctx.provider && ctx.model) {
    args.push("--provider", ctx.provider.name);
    args.push("--model", ctx.model.name);
  } else if (ctx.model) {
    args.push("--model", ctx.model.name);
  }
  // Native resume: pass the harness's own session reference (spec v1 §3).
  if (ctx.runtimeSession?.nativeSessionRef) {
    args.push("--session", ctx.runtimeSession.nativeSessionRef);
  } else {
    args.push("--no-session");
  }
  const tools = ctx.task.policy?.toolPermissions;
  if (tools && tools.length > 0) {
    args.push("--tools", tools.join(","));
  }
  if (ctx.task.policy?.shell === "deny") {
    args.push("--no-tools");
  }
  if (ctx.runtime.config?.thinking) args.push("--thinking", String(ctx.runtime.config.thinking));
  return args;
}

/**
 * Pi Agent Runtime adapter.
 *
 * One execution loop for both backends (v2 §7/§8/§10): the adapter
 * builds the `pi --print --mode json` command and hands it to the
 * execution backend — a local process or a Docker container. Either
 * way, the JSONL stdout is parsed here with the same mapper, the native
 * session id is extracted, and a stored native session reference is
 * resumed via `--session`.
 *
 * Containerized runs mount the runtime's opaque native-state directory
 * at pi's home path so native sessions survive container destruction.
 */
export const piAdapter: AgentRuntimeAdapter = {
  kind: "pi",
  name: "Pi Agent",
  capabilities: piCapabilities,
  containerizedCapabilities: piContainerizedCapabilities,
  nativeStateMountPath: "/root/.pi",

  async run(ctx: RuntimeContext): Promise<RuntimeResult> {
    // This run's instruction: the rendered handoff for continuity runs,
    // otherwise the task's original prompt (spec v1 §20 Inject Handoff).
    const prompt = ctx.run.inputInstruction ?? ctx.task.prompt;
    return runHarnessCommand(ctx, {
      bin: piBin(),
      args: buildArgs(ctx),
      prompt,
      source: "pi",
      image: ctx.runtime.image ?? "node:22-alpine",
      workspaceContainerPath: "/workspace",
      mapLine: mapPiEvent,
      extractSessionRef: extractPiSessionRef,
    });
  },

  async cancel(ctx) {
    await ctx.log("Pi run cancelled", "warn");
  },

  describe() {
    return { needsDocker: false, needsModel: false, cli: piBin() };
  },
};
